#!/usr/bin/env bash
#
# Obtain the LLVM 23.1.1 headers the jev-opt pass plugins are compiled
# against, without building LLVM itself.
#
# The pinned toolchain (nightly-2026-09-21) ships LLVM 23.1.1 as a shared
# library, so the plugin links against nothing: it only needs headers that
# match the host's ABI exactly (results.md Day 0 section 2, decisions 9).
# Part of that header set is generated by tablegen at configure/build time,
# so a CMake configure plus the `intrinsics_gen` target is the minimum that
# produces a usable include tree. No LLVM library is ever compiled.
#
# Everything lands under third_party/ (git-ignored):
#
#   third_party/llvm-project-23.1.1.src/llvm/include   checked-in headers
#   third_party/llvm-build/include                     generated headers
#
# Idempotent: every stage is skipped when its output already exists. Pass
# --force to redo from the tarball.
set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TP="$REPO/third_party"
VER=23.1.1
SRC="$TP/llvm-project-$VER.src"
BUILD="$TP/llvm-build"
TARBALL="$TP/llvm-project-$VER.src.tar.xz"
URL="https://github.com/llvm/llvm-project/releases/download/llvmorg-$VER/llvm-project-$VER.src.tar.xz"
TARBALL_SHA256=ebe9be46fe8756d58c5b198ffad0fa2a766257add81a4dc52179bfacc7888ee6

# This machine has a Windows CMake 3.19 ahead of the Debian one on PATH
# (/usr/local/bin/cmake, an MSVC build that cannot configure LLVM), so the
# tools are named explicitly rather than taken from PATH. Override with
# CMAKE= / NINJA= on a machine where the PATH entries are the right ones.
CMAKE="${CMAKE:-/usr/bin/cmake}"
NINJA="${NINJA:-ninja}"

FORCE=0
[ "${1:-}" = --force ] && FORCE=1

mkdir -p "$TP"

# 1. Tarball. The release asset, not a clone: a shallow clone of
#    llvm-project is larger and the tag is what we want pinned.
if [ "$FORCE" = 1 ] || [ ! -f "$TARBALL" ]; then
  echo "== fetching $URL"
  # -C - resumes a partial .part, so an interrupted fetch of the 179 MB
  # asset does not start over. xz -t before the rename, so a truncated
  # download can never be mistaken for a good tarball on the next run.
  curl -fsSL --retry 3 -C - -o "$TARBALL.part" "$URL"
  xz -t "$TARBALL.part"
  mv "$TARBALL.part" "$TARBALL"
fi

# 1b. Integrity of whatever tarball we ended up with. Recorded from the
#     fetch of 2026-09-22; a mismatch means the release asset changed.
if [ -n "${JEV_SKIP_SHA:-}" ]; then
  echo "== skipping tarball sha256 check (JEV_SKIP_SHA set)"
else
  echo "$TARBALL_SHA256  $TARBALL" | sha256sum -c -
fi

# 2. Extract only what a CMake configure of the llvm project needs. The
#    other subprojects (clang, mlir, ...) are several GB and unused.
#
#    libc/ is not optional in 23.x: llvm/CMakeLists.txt:725 hard-errors when
#    FindLibcCommonUtils cannot see the sibling libc/ directory, and some
#    llvm/ADT headers include libc/shared/*.h through that include path. It
#    is only ever used as a header directory here; nothing in it is built.
if [ "$FORCE" = 1 ] || [ ! -d "$SRC/llvm/include/llvm" ] || [ ! -d "$SRC/libc" ]; then
  echo "== extracting llvm/, cmake/, third-party/, libc/"
  rm -rf "$SRC"
  mkdir -p "$SRC"
  tar -xJf "$TARBALL" -C "$TP" \
      "llvm-project-$VER.src/llvm" \
      "llvm-project-$VER.src/cmake" \
      "llvm-project-$VER.src/third-party" \
      "llvm-project-$VER.src/libc"
fi

# 3. Configure. The three settings below are the ones that reach the
#    headers, and each has to match the host libLLVM.so:
#      LLVM_ENABLE_ASSERTIONS=OFF          -> NDEBUG-shaped headers
#      LLVM_ABI_BREAKING_CHECKS=FORCE_OFF  -> abi-breaking.h picks
#                                             DisableABIBreakingChecks, which
#                                             is the symbol the host defines
#                                             (results.md Day 0 section 2)
#
#    NOTE on the second one: the option is LLVM_ABI_BREAKING_CHECKS.
#    SPEC.ja.md 8.2 and the day-3 brief both name it
#    LLVM_ENABLE_ABI_BREAKING_CHECKS, which is the *output* variable, not the
#    option. Setting that one does not switch the checks off --- it lands in
#    the cache as the string "FORCE_OFF", which the
#    `#cmakedefine01 LLVM_ENABLE_ABI_BREAKING_CHECKS` in abi-breaking.h.cmake
#    evaluates as true, so the generated header says
#    `#define LLVM_ENABLE_ABI_BREAKING_CHECKS 1` and every translation unit
#    ends up referencing llvm::EnableABIBreakingChecks --- a symbol the host
#    libLLVM does not define, because it was built with assertions off. The
#    plugin then fails to dlopen. -U removes a stale cache entry from a build
#    directory configured with the wrong name.
#      LLVM_TARGETS_TO_BUILD=X86           -> only affects how much tablegen
#                                             runs; the host is x86-64 only
if [ "$FORCE" = 1 ] || [ ! -f "$BUILD/build.ninja" ]; then
  echo "== configuring"
  "$CMAKE" -G Ninja -S "$SRC/llvm" -B "$BUILD" \
    -DCMAKE_BUILD_TYPE=Release \
    -DLLVM_TARGETS_TO_BUILD=X86 \
    -DLLVM_ENABLE_ASSERTIONS=OFF \
    -DLLVM_ABI_BREAKING_CHECKS=FORCE_OFF \
    -ULLVM_ENABLE_ABI_BREAKING_CHECKS \
    -DLLVM_ENABLE_ZLIB=OFF -DLLVM_ENABLE_ZSTD=OFF \
    -DLLVM_ENABLE_LIBXML2=OFF -DLLVM_ENABLE_TERMINFO=OFF \
    -DLLVM_INCLUDE_TESTS=OFF -DLLVM_INCLUDE_BENCHMARKS=OFF \
    -DLLVM_INCLUDE_EXAMPLES=OFF
fi

# 4. Generated headers only. These are the tablegen targets that produce
#    everything under build/include that llvm/Passes/PassBuilder.h reaches:
#
#      intrinsics_gen      Intrinsics*.h, IntrinsicEnums.inc, Attributes.inc,
#                          RuntimeLibcalls.inc
#      analysis_gen        TargetLibraryInfo.inc
#      vt_gen              CodeGen/GenVT.inc
#      target_parser_gen   TargetParser/*Def.inc
#      omp_gen / acc_gen   Frontend/OpenMP, Frontend/OpenACC
#      llvm_vcsrevision_h  Support/VCSRevision.h
#
#    They pull in llvm-tblgen (TableGen + Support, a couple of minutes), but
#    no LLVM library target is in their dependency graph, so LLVM itself is
#    still not built. SPEC.ja.md 8.2 names only intrinsics_gen; that alone is
#    not enough, because PassBuilder.h -> CGSCCPassManager.h ->
#    LazyCallGraph.h -> TargetLibraryInfo.h needs TargetLibraryInfo.inc.
echo "== ninja <tablegen header targets>"
"$NINJA" -C "$BUILD" intrinsics_gen analysis_gen vt_gen target_parser_gen \
                     omp_gen acc_gen llvm_vcsrevision_h

echo
echo "include paths:"
echo "  $SRC/llvm/include"
echo "  $BUILD/include"
