#!/usr/bin/env python3
"""Enumerate every input inside the jaq repository that can drive the jaq CLI.

This is the candidate pool for Experiment 1 (results.md "Experiment 1 (jaq)"):
the set a `jev-opt build` selector would choose its PGO training workload
from, without the user writing a single training input. Nothing here is
generated by us --- every item comes out of `targets/jaq/src`.

Six sources, in the order a selector would plausibly discover them:

  doctest   `FILTER --> EXPECTED` code spans in docs/*.dj. This is exactly
            what the repository's own docs/tests.jq extracts and feeds to
            `jaq --run-tests`; the input is always `null`.
  doccli    `$ producer | jaq ARGS` shell examples in docs/*.dj, which
            docs/cli-tests.jq extracts and docs/shelltest.rs runs. Only the
            pipelines that reduce to exactly (producer -> jaq) are kept; the
            producer is executed here to obtain the stdin bytes, so no shell
            is involved when an arm runs.
  test      give/gives/yields!/fail calls in jaq-{core,std,json,fmts}/tests.
            These drive the *library*, not the CLI; an item is the CLI
            equivalent `jaq FILTER` with the test's input on stdin.
  clitest   test!(name, &[args], input, output) in jaq/tests/golden.rs, which
            already spawns the real binary.
  bench     examples/benches/*.jq x the `n` in examples/benches.json, driven
            exactly as bench.sh drives them (`echo $n | jaq "$(cat f.jq) |
            length"`), plus bench.sh's three hand-written benchmarks.
  example   the runnable example programs under examples/.

Subcommands:
  extract   parse everything, dry-run each candidate against a jaq binary
            with a timeout, and write targets/jaq/pool/pool.json.
  select    print the ids belonging to a named arm.
  run       run a set of ids against a binary (this is what an arm's training
            run is; scripts/pgo_train_arm.sh calls it).

Python 3 standard library only.
"""

import argparse
import base64
import collections
import json
import os
import re
import shlex
import subprocess
import sys
import time

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(REPO, "targets/jaq/src")
POOL_DIR = os.path.join(REPO, "targets/jaq/pool")
POOL_JSON = os.path.join(POOL_DIR, "pool.json")
GEN_DIR = os.path.join(POOL_DIR, "gen")

# Counters for "how many were extractable", reported by `extract`.
SKIPPED = collections.Counter()


def rel(path):
    return os.path.relpath(path, REPO)


# ---------------------------------------------------------------------------
# Rust literal helpers
# ---------------------------------------------------------------------------

def rust_string_at(s, i):
    """Parse the Rust string literal starting at s[i]; return (value, end)."""
    m = re.compile(r'r(#*)"').match(s, i)
    if m:
        hashes = m.group(1)
        close = '"' + hashes
        end = s.index(close, m.end())
        return s[m.end():end], end + len(close)
    if s[i] != '"':
        raise ValueError(f"not a string literal at {i}: {s[i:i+20]!r}")
    out = []
    j = i + 1
    while s[j] != '"':
        if s[j] == "\\":
            c = s[j + 1]
            out.append({"n": "\n", "t": "\t", "r": "\r", "0": "\0",
                        "\\": "\\", '"': '"', "'": "'"}.get(c, c))
            if c == "u":
                m = re.compile(r"u\{([0-9a-fA-F]+)\}").match(s, j + 1)
                out[-1] = chr(int(m.group(1), 16))
                j = m.end()
                continue
            j += 2
            continue
        out.append(s[j])
        j += 1
    return "".join(out), j + 1


def balanced(s, i, open_ch="(", close_ch=")"):
    """s[i] is open_ch; return (inner text, index just past close_ch)."""
    depth = 0
    j = i
    while True:
        c = s[j]
        if c in "\"" or (c == "r" and re.compile(r'r#*"').match(s, j)):
            try:
                _, j = rust_string_at(s, j)
                continue
            except (ValueError, IndexError):
                pass
        if c == "'" and j + 2 < len(s) and (s[j + 2] == "'" or s[j + 1] == "\\"):
            j = s.index("'", j + 1) + 1          # char literal
            continue
        if c in "([{":
            depth += 1
        elif c in ")]}":
            depth -= 1
            if depth == 0:
                return s[i + 1:j], j + 1
        j += 1


def split_args(inner):
    """Split a call's argument list on top-level commas."""
    parts, depth, start, j = [], 0, 0, 0
    while j < len(inner):
        c = inner[j]
        if c == '"' or (c == "r" and re.compile(r'r#*"').match(inner, j)):
            try:
                _, j = rust_string_at(inner, j)
                continue
            except (ValueError, IndexError):
                pass
        if c in "([{":
            depth += 1
        elif c in ")]}":
            depth -= 1
        elif c == "," and depth == 0:
            parts.append(inner[start:j])
            start = j + 1
        j += 1
    parts.append(inner[start:])
    return [p.strip() for p in parts if p.strip()]


def json_arg(text):
    """`json!(X)` or a bare JSON-ish Rust expression -> compact JSON text."""
    text = text.strip()
    m = re.match(r"^json!\s*", text)
    if m:
        inner, _ = balanced(text, m.end())
        text = inner.strip()
    if text.startswith("r") and re.match(r'^r#*"', text):
        try:
            v, _ = rust_string_at(text, 0)
            return json.dumps(v)
        except (ValueError, IndexError):
            return None
    if text.startswith('"'):
        try:
            v, _ = rust_string_at(text, 0)
            return json.dumps(v)
        except (ValueError, IndexError):
            return None
    # json!() bodies are JSON with Rust escapes already resolved by the
    # tokenizer; everything that is not literal JSON (a Rust variable, a
    # helper call, a format string) is dropped and counted.
    try:
        return json.dumps(json.loads(text), separators=(",", ":"))
    except (ValueError, TypeError):
        return None


def filter_arg(text):
    text = text.strip()
    if text.startswith('"') or re.match(r'^r#*"', text):
        try:
            v, _ = rust_string_at(text, 0)
            return v
        except (ValueError, IndexError):
            return None
    return None


# ---------------------------------------------------------------------------
# sources
# ---------------------------------------------------------------------------

FENCE = re.compile(r"^(```+|~~~+).*?^\1", re.M | re.S)
CODESPAN = re.compile(r"(`+)(?!`)(.+?)(?<!`)\1(?!`)", re.S)


def dj_files():
    return sorted(f for f in os.listdir(os.path.join(SRC, "docs"))
                  if f.endswith(".dj"))


def extract_doctests():
    """`FILTER --> EXPECTED` code spans, the way docs/tests.jq reads them."""
    items = []
    for name in dj_files():
        path = os.path.join(SRC, "docs", name)
        text = open(path, encoding="utf-8").read()
        # Fenced blocks are prose/XML/shell, never doc tests; dropping them
        # also removes the one `<!-- ... -->` XML comment in formats.dj.
        body = FENCE.sub(lambda m: "\n" * m.group(0).count("\n"), text)
        for m in CODESPAN.finditer(body):
            span = m.group(2)
            if "-->" not in span:
                continue
            line = body.count("\n", 0, m.start()) + 1
            filt = span.split("-->")[0]
            filt = re.sub(r"#[^\n]*", "", filt)      # docs/tests.jq
            filt = " ".join(filt.split())
            if not filt:
                SKIPPED["doctest:empty-filter"] += 1
                continue
            items.append(dict(
                source="doctest", origin=f"docs/{name}:{line}",
                argv=[filt], stdin="null\n", cwd="targets/jaq/src",
                description=f"manual doc test: {filt[:60]}"))
    return items


PRODUCERS = {"echo": "/usr/bin/echo", "printf": "/usr/bin/printf",
             "seq": "/usr/bin/seq"}


def extract_doccli():
    """`$ producer | jaq ARGS` lines, the way docs/cli-tests.jq reads them."""
    items = []
    for name in dj_files():
        path = os.path.join(SRC, "docs", name)
        lines = open(path, encoding="utf-8").read().split("\n")
        for i, raw in enumerate(lines, 1):
            if not raw.startswith("$ "):
                continue
            cmd = raw[2:]
            j = i
            while cmd.endswith("\\"):                # shelltest.rs continuation
                cmd = cmd[:-1] + lines[j]
                j += 1
            try:
                lx = shlex.shlex(cmd, posix=True, punctuation_chars=True)
                lx.whitespace_split = True
                toks = list(lx)
            except ValueError:
                SKIPPED["doccli:unparsable"] += 1
                continue
            if any(t in (";", "&&", "||", ">", ">>", "<", "&") for t in toks):
                SKIPPED["doccli:shell-control"] += 1   # writes files, $?, ...
                continue
            stages, cur = [], []
            for t in toks:
                if t == "|":
                    stages.append(cur)
                    cur = []
                else:
                    cur.append(t)
            stages.append(cur)
            stages = [s for s in stages if s]
            if not stages or stages[-1][0] != "jaq":
                SKIPPED["doccli:not-jaq-last"] += 1
                continue
            if len(stages) == 1:
                argv, stdin = stages[0][1:], ""
                if "-n" not in "".join(argv) and not any(
                        a.endswith(".json") or a.endswith(".xhtml")
                        for a in argv):
                    SKIPPED["doccli:would-block-on-stdin"] += 1
                    continue
            elif len(stages) == 2 and stages[0][0] in PRODUCERS:
                prod = [PRODUCERS[stages[0][0]]] + stages[0][1:]
                try:
                    out = subprocess.run(prod, capture_output=True, timeout=5)
                except (OSError, subprocess.TimeoutExpired):
                    SKIPPED["doccli:producer-failed"] += 1
                    continue
                stdin = out.stdout.decode("utf-8", "surrogateescape")
                argv = stages[-1][1:]
            else:
                SKIPPED["doccli:multi-stage"] += 1     # jaq | jaq, yes | ...
                continue
            items.append(dict(
                source="doccli", origin=f"docs/{name}:{i}",
                argv=argv, stdin=stdin, cwd="targets/jaq/src",
                description=f"manual CLI example: {cmd[:70]}"))
    return items


TEST_FILES = [
    "jaq-core/tests/tests.rs", "jaq-core/tests/defs.rs",
    "jaq-core/tests/funs.rs", "jaq-core/tests/path.rs",
    "jaq-std/tests/defs.rs", "jaq-std/tests/funs.rs",
    "jaq-json/tests/defs.rs", "jaq-json/tests/funs.rs",
    "jaq-fmts/tests/formats.rs", "jaq-fmts/tests/funs.rs",
]

CALL = re.compile(r"\b(give|gives|fail)\s*\(")
YIELDS = re.compile(r"\byields!\s*\(")


def extract_rust_tests():
    """give(input, filter, out) / gives / fail / yields!(name, filter, out)."""
    items = []
    for f in TEST_FILES:
        path = os.path.join(SRC, f)
        text = open(path, encoding="utf-8").read()
        for m in CALL.finditer(text):
            try:
                inner, _ = balanced(text, m.end() - 1)
            except (ValueError, IndexError):
                SKIPPED["test:unbalanced"] += 1
                continue
            args = split_args(inner)
            if len(args) < 2:
                SKIPPED["test:too-few-args"] += 1
                continue
            inp, filt = json_arg(args[0]), filter_arg(args[1])
            if inp is None:
                SKIPPED["test:input-not-literal"] += 1
                continue
            if filt is None:
                SKIPPED["test:filter-not-literal"] += 1
                continue
            line = text.count("\n", 0, m.start()) + 1
            items.append(dict(
                source="test", origin=f"{f}:{line}",
                argv=[" ".join(filt.split())], stdin=inp + "\n",
                cwd="targets/jaq/src",
                description=f"{m.group(1)}(): {filt[:60]}"))
        for m in YIELDS.finditer(text):
            try:
                inner, _ = balanced(text, m.end() - 1)
            except (ValueError, IndexError):
                SKIPPED["test:unbalanced"] += 1
                continue
            args = split_args(inner)
            if len(args) < 2:
                SKIPPED["test:too-few-args"] += 1
                continue
            filt = filter_arg(args[1])
            if filt is None:
                SKIPPED["test:filter-not-literal"] += 1
                continue
            line = text.count("\n", 0, m.start()) + 1
            items.append(dict(
                source="test", origin=f"{f}:{line}",
                argv=[" ".join(filt.split())], stdin="null\n",
                cwd="targets/jaq/src",
                description=f"yields!(): {filt[:60]}"))
    return items


def extract_golden():
    """jaq/tests/golden.rs --- the repository's own CLI tests."""
    path = os.path.join(SRC, "jaq/tests/golden.rs")
    text = open(path, encoding="utf-8").read()
    consts = {}
    for m in re.finditer(r'const\s+(\w+)\s*:\s*&str\s*=\s*', text):
        v, _ = rust_string_at(text, m.end())
        consts[m.group(1)] = v
    items = []
    for m in re.finditer(r"\btest!\s*\(", text):
        inner, _ = balanced(text, m.end() - 1)
        args = split_args(inner)
        if len(args) < 3:
            SKIPPED["clitest:too-few-args"] += 1
            continue
        name = args[0].strip()
        arr = args[1].strip()
        if not arr.startswith("&["):
            SKIPPED["clitest:args-not-array"] += 1
            continue
        argv = []
        bad = False
        for a in split_args(balanced(arr, 1, "[", "]")[0]):
            v = filter_arg(a)
            if v is None:
                bad = True
                break
            argv.append(v)
        if bad:
            SKIPPED["clitest:arg-not-literal"] += 1
            continue
        raw = args[2].strip()
        stdin = consts.get(raw) if raw in consts else filter_arg(raw)
        if stdin is None:
            SKIPPED["clitest:input-not-literal"] += 1
            continue
        line = text.count("\n", 0, m.start()) + 1
        items.append(dict(
            source="clitest", origin=f"jaq/tests/golden.rs:{line}",
            argv=argv, stdin=stdin,
            cwd="targets/jaq/src/jaq",   # -L tests, --rawfile tests/256.bin
            description=f"golden CLI test {name}"))
    return items


def extract_bench():
    """examples/benches/*.jq x examples/benches.json, driven as bench.sh does.

    bench.sh runs `echo $n | jaq "$(cat examples/benches/$b.jq) | length"`.
    The trailing `| length` is load-bearing: without it a benchmark at
    n = 1048576 writes a million values to stdout.
    """
    items = []
    path = os.path.join(SRC, "examples/benches.json")
    for line in open(path, encoding="utf-8"):
        line = line.strip()
        if not line:
            continue
        spec = json.loads(line)
        name, n = spec["name"], spec["n"]
        jq = os.path.join(SRC, "examples/benches", name + ".jq")
        if not os.path.exists(jq):
            SKIPPED["bench:no-jq-file"] += 1
            continue
        filt = open(jq, encoding="utf-8").read().strip() + " | length"
        items.append(dict(
            source="bench", origin=f"examples/benches/{name}.jq",
            argv=[filt], stdin=f"{n}\n", cwd="targets/jaq/src",
            description=f"bench.sh benchmark {name}, n={n}"))
    # bench.sh's three hand-written benchmarks. `empty` is run 512 times by
    # bench.sh purely to time process startup; one invocation is the item.
    items.append(dict(
        source="bench", origin="bench.sh:empty",
        argv=["-n", "empty"], stdin="", cwd="targets/jaq/src",
        description="bench.sh startup benchmark `empty`"))
    items.append(dict(
        source="bench", origin="bench.sh:bf-fib",
        argv=["-sRrf", "examples/bf.jq", "examples/fib.bf"], stdin="",
        cwd="targets/jaq/src",
        description="bench.sh bf-fib: a Brainfuck interpreter in jq"))
    # bench.sh's `defs` benchmark generates 100000 `def a: 0;` lines into a
    # process substitution. The generated file is the only large *input* the
    # repository produces, and it is a program, not data.
    os.makedirs(GEN_DIR, exist_ok=True)
    defs = os.path.join(GEN_DIR, "defs100k.jq")
    if not os.path.exists(defs):
        with open(defs, "w") as fh:
            fh.write("def a: 0;\n" * 100000)
            fh.write("empty\n")
    items.append(dict(
        source="bench", origin="bench.sh:defs",
        argv=["-n", "-f", rel(defs)], stdin="", cwd=".",
        description="bench.sh defs: parse 100000 filter definitions"))
    return items


def extract_examples():
    """Runnable example programs under examples/."""
    items = [dict(
        source="example", origin="examples/ball.sh",
        argv=["-nc", "-L", "examples",
              'include "ball"; {x: 50, y: 200, r: 25, col: [0, 255, 0], '
              'vx: 2.5, vy: 0} | animate_ball(9600; 1/100) '
              '| select(.step % 100 == 0)'],
        stdin="", cwd="targets/jaq/src",
        description="examples/ball.sh: 9600-step ball animation"),
        dict(
        source="example", origin="examples/table.jq",
        argv=["-L", "examples", "-f", "examples/table.jq", "--from", "xml",
              "examples/test.xhtml"],
        stdin="", cwd="targets/jaq/src",
        description="examples/table.jq on examples/test.xhtml"),
        dict(
        source="example", origin="examples/bottles.jq",
        argv=["-nr", "-f", "examples/bottles.jq"], stdin="",
        cwd="targets/jaq/src",
        description="examples/bottles.jq: 99 bottles of beer"),
        dict(
        source="example", origin="examples/bf.jq",
        argv=["-sRrf", "examples/bf.jq", "examples/hello.bf"], stdin="",
        cwd="targets/jaq/src",
        description="examples/bf.jq on hello.bf")]
    return items


# ---------------------------------------------------------------------------
# extract
# ---------------------------------------------------------------------------

def file_args(item):
    """Existing files named on the command line, resolved against cwd."""
    out = []
    base = os.path.join(REPO, item["cwd"])
    for a in item["argv"]:
        p = os.path.join(base, a)
        if a and not a.startswith("-") and os.path.isfile(p):
            out.append(p)
    return out


def cmd_extract(args):
    items = []
    items += extract_doctests()
    items += extract_doccli()
    items += extract_rust_tests()
    items += extract_golden()
    items += extract_bench()
    items += extract_examples()

    per = collections.Counter()
    for it in items:
        per[it["source"]] += 1
        it["id"] = f"{it['source']}-{per[it['source']]:04d}"
        nonflag = [a for a in it["argv"] if not a.startswith("-")]
        it["filter"] = max(nonflag, key=len) if nonflag else ""
        fa = file_args(it)
        it["input_paths"] = [rel(p) for p in fa]
        it["input_bytes"] = (len(it["stdin"].encode("utf-8", "surrogateescape"))
                             + sum(os.path.getsize(p) for p in fa))
        it["filter_bytes"] = len(it["filter"].encode("utf-8"))

    print(f"parsed {len(items)} candidates")
    for k, v in sorted(SKIPPED.items()):
        print(f"  skipped {k}: {v}")

    # Dry run: a candidate that cannot terminate cannot train anything. A
    # non-zero exit is kept --- fail() tests and `try ... catch` doc tests are
    # supposed to fail, and they still execute the code we care about.
    binary = os.path.abspath(args.binary)
    kept = []
    for n, it in enumerate(items, 1):
        r = run_item(binary, it, timeout=args.timeout, env=None)
        it["dry_status"] = r["status"]
        it["dry_rc"] = r["rc"]
        it["dry_ms"] = r["ms"]
        it["dry_stdout_bytes"] = r["out_bytes"]
        if r["status"] == "ok":
            kept.append(it)
        if args.progress and n % 200 == 0:
            print(f"  dry run {n}/{len(items)}", file=sys.stderr, flush=True)

    dropped = [it for it in items if it["dry_status"] != "ok"]
    print(f"dry run: {len(kept)} usable, {len(dropped)} dropped")
    bys = collections.Counter((it["source"], it["dry_status"])
                              for it in dropped)
    for (s, st), c in sorted(bys.items()):
        print(f"  dropped {s}/{st}: {c}")

    os.makedirs(POOL_DIR, exist_ok=True)
    doc = {"schema_version": 1,
           "repo_commit": subprocess.run(
               ["git", "-C", SRC, "rev-parse", "HEAD"],
               capture_output=True, text=True).stdout.strip(),
           "dry_run_binary": rel(binary),
           "dry_run_timeout_s": args.timeout,
           "parsed": len(items), "usable": len(kept),
           "skipped_at_parse": dict(SKIPPED),
           "items": kept,
           "dropped": [{k: it[k] for k in
                        ("id", "source", "origin", "dry_status", "dry_rc",
                         "description")} for it in dropped]}
    with open(POOL_JSON, "w") as fh:
        json.dump(doc, fh, indent=1)
    print(f"wrote {rel(POOL_JSON)}")
    report(kept)


def report(items):
    per = collections.Counter(it["source"] for it in items)
    print("\npool by source:")
    for s, c in sorted(per.items()):
        b = [it["input_bytes"] for it in items if it["source"] == s]
        ms = [it["dry_ms"] for it in items if it["source"] == s]
        print(f"  {s:9s} n={c:5d}  input bytes min/median/max "
              f"{min(b)}/{sorted(b)[len(b)//2]}/{max(b)}  "
              f"dry ms min/median/max "
              f"{min(ms):.0f}/{sorted(ms)[len(ms)//2]:.0f}/{max(ms):.0f}")
    b = sorted(it["input_bytes"] for it in items)
    print(f"\ninput-byte distribution over all {len(b)} items:")
    for q in (0, 10, 25, 50, 75, 90, 99, 100):
        print(f"  p{q:<3d} {b[min(len(b) - 1, q * len(b) // 100)]}")
    print(f"  total input bytes {sum(b)}")
    ms = sorted(it["dry_ms"] for it in items)
    print(f"  total dry-run wall time {sum(ms) / 1000:.1f} s, "
          f"median item {ms[len(ms) // 2]:.1f} ms")


# ---------------------------------------------------------------------------
# arms
# ---------------------------------------------------------------------------

def load_pool():
    return json.load(open(POOL_JSON))


def arm_items(arm, items, keep_poison=False):
    """The subset of the pool an arm trains on.

    Items flagged `poisons_profile` are excluded from every arm unless
    keep_poison is set: they write a pointer-shaped value into one of the
    instrumented binary's counters (see `scan`), which makes that one block
    hold 99.999% of the profile and moves LLVM's whole hot/cold cutoff. The
    `T_allraw` arm is `T_all` with them left in, which is what a selector
    with no such guard would really produce.
    """
    if arm == "T_allraw":
        arm, keep_poison = "T_all", True
    if not keep_poison:
        items = [i for i in items if not i.get("poisons_profile")]
    if arm == "T_all":
        return list(items)
    if arm == "T_readme":
        return [i for i in items if i["source"] in ("doctest", "doccli")]
    if arm == "T_big":
        # Top 10% by input bytes --- the naive "train on the big inputs" rule.
        s = sorted(items, key=lambda i: -i["input_bytes"])
        return s[:max(1, len(s) // 10)]
    if arm == "T_bench":
        return [i for i in items if i["source"] in ("bench", "example")]
    if arm == "T_tests":
        return [i for i in items if i["source"] in ("test", "clitest")]
    raise SystemExit(f"unknown arm {arm!r}")


# ---------------------------------------------------------------------------
# scan: find pool items that corrupt the instrumented binary's counters
# ---------------------------------------------------------------------------

# No block of jaq can be executed 1e11 times by an item that finishes in a few
# milliseconds; anything at or above this is not a count.
POISON_THRESHOLD = 10 ** 11


def _max_block(llvm_profdata, gen_bin, sub, scratch, timeout):
    raw = os.path.join(scratch, "raw")
    os.makedirs(raw, exist_ok=True)
    for f in os.listdir(raw):
        os.remove(os.path.join(raw, f))
    env = dict(os.environ)
    env["LLVM_PROFILE_FILE"] = os.path.join(raw, "%m.profraw")
    for it in sub:
        run_item(gen_bin, it, timeout=timeout, env=env)
    merged = os.path.join(scratch, "scan.profdata")
    subprocess.run([llvm_profdata, "merge", "-o", merged] +
                   [os.path.join(raw, f) for f in os.listdir(raw)], check=True)
    out = subprocess.run([llvm_profdata, "show", merged],
                         capture_output=True, text=True, check=True).stdout
    return int(re.search(r"Maximum internal block count: (\d+)", out).group(1))


def cmd_scan(args):
    """Bisect the pool for items whose profraw contains an impossible count.

    Three items in jaq v3.1.1 do: each one runs `tostring` on a big integer,
    which reaches num_bigint's `to_radix_le`, and under `-Cprofile-generate`
    that function writes a *pointer* (0x200000000000-ish, mimalloc's arena
    region) into one of its own counter slots. The value differs run to run
    in its low bits, so it is a wild write and not a count. One such block
    holds 99.999% of the merged profile's total, and `llvm-profdata show
    --detailed-summary` then puts every profile-summary percentile on that
    one block --- i.e. LLVM's hot/cold cutoff is set by garbage and the rest
    of the program is cold. Not visible in the released (uninstrumented)
    binary.
    """
    pool = load_pool()
    items = pool["items"]
    tool = args.llvm_profdata or default_llvm_profdata()
    gen = os.path.abspath(args.binary)
    scratch = args.scratch
    os.makedirs(scratch, exist_ok=True)

    def find(sub):
        if not sub or _max_block(tool, gen, sub, scratch,
                                 args.timeout) < POISON_THRESHOLD:
            return []
        if len(sub) == 1:
            return sub
        h = len(sub) // 2
        return find(sub[:h]) + find(sub[h:])

    bad = []
    for i in range(0, len(items), args.chunk):
        ch = items[i:i + args.chunk]
        m = _max_block(tool, gen, ch, scratch, args.timeout)
        print(f"chunk {i:5d}-{i + len(ch):5d} max block count {m}", flush=True)
        if m >= POISON_THRESHOLD:
            for b in find(ch):
                bad.append(b)
                print(f"   POISONS THE PROFILE: {b['id']} {b['origin']} "
                      f"| {b['filter'][:80]}", flush=True)
    ids = {b["id"] for b in bad}
    for it in items:
        it["poisons_profile"] = it["id"] in ids
    pool["poisoning_items"] = sorted(ids)
    with open(POOL_JSON, "w") as fh:
        json.dump(pool, fh, indent=1)
    print(f"\n{len(ids)} of {len(items)} pool items poison the profile; "
          f"flagged in {rel(POOL_JSON)}")


def default_llvm_profdata():
    sysroot = subprocess.run(["rustc", "--print", "sysroot"],
                             capture_output=True, text=True,
                             check=True).stdout.strip()
    triple = re.search(r"^host: (.*)$",
                       subprocess.run(["rustc", "-vV"], capture_output=True,
                                      text=True, check=True).stdout,
                       re.M).group(1)
    return f"{sysroot}/lib/rustlib/{triple}/bin/llvm-profdata"


def cmd_select(args):
    pool = load_pool()
    sel = arm_items(args.arm, pool["items"])
    if args.count:
        print(len(sel))
        return
    if args.sources:
        c = collections.Counter(i["source"] for i in sel)
        print(f"{args.arm}: n={len(sel)} "
              f"dry_wall={sum(i['dry_ms'] for i in sel) / 1000:.2f}s "
              f"input_bytes={sum(i['input_bytes'] for i in sel)} "
              + " ".join(f"{k}={v}" for k, v in sorted(c.items())))
        return
    for it in sel:
        print(it["id"])


# ---------------------------------------------------------------------------
# run
# ---------------------------------------------------------------------------

def run_item(binary, it, timeout, env):
    cwd = os.path.join(REPO, it["cwd"])
    argv = [binary] + it["argv"]
    data = it["stdin"].encode("utf-8", "surrogateescape")
    t0 = time.perf_counter()
    try:
        p = subprocess.run(argv, input=data, cwd=cwd, env=env,
                           stdout=subprocess.PIPE, stderr=subprocess.DEVNULL,
                           timeout=timeout)
        ms = (time.perf_counter() - t0) * 1000
        return {"status": "ok", "rc": p.returncode, "ms": ms,
                "out_bytes": len(p.stdout)}
    except subprocess.TimeoutExpired:
        return {"status": "timeout", "rc": None,
                "ms": (time.perf_counter() - t0) * 1000, "out_bytes": 0}
    except OSError as e:
        return {"status": f"oserror:{e.errno}", "rc": None,
                "ms": (time.perf_counter() - t0) * 1000, "out_bytes": 0}


def cmd_run(args):
    pool = load_pool()
    sel = arm_items(args.arm, pool["items"])
    binary = os.path.abspath(args.binary)
    env = dict(os.environ)
    if args.profile_file:
        # Every arm writes to its own directory. The instrumented binary's
        # baked-in path is the frozen pgo/jaq/profraw/, which must not be
        # touched, so this is never optional for that binary.
        env["LLVM_PROFILE_FILE"] = os.path.abspath(args.profile_file)
    log = []
    t0 = time.perf_counter()
    for n, it in enumerate(sel, 1):
        r = run_item(binary, it, timeout=args.timeout, env=env)
        log.append({"id": it["id"], **r})
        if args.progress and n % 100 == 0:
            print(f"  {args.arm}: {n}/{len(sel)}", file=sys.stderr, flush=True)
    wall = time.perf_counter() - t0
    bad = [r for r in log if r["status"] != "ok"]
    print(f"arm {args.arm}: {len(sel)} invocations, {wall:.1f} s wall, "
          f"{len(bad)} did not terminate normally")
    if args.log:
        with open(args.log, "w") as fh:
            json.dump({"arm": args.arm, "n": len(sel), "wall_s": wall,
                       "runs": log}, fh, indent=1)


def main():
    p = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = p.add_subparsers(dest="cmd", required=True)

    e = sub.add_parser("extract")
    e.add_argument("--binary", required=True,
                   help="a plain (non-instrumented) jaq for the dry run")
    e.add_argument("--timeout", type=float, default=5.0)
    e.add_argument("--progress", action="store_true")
    e.set_defaults(fn=cmd_extract)

    sc = sub.add_parser("scan")
    sc.add_argument("--binary", required=True,
                    help="the INSTRUMENTED jaq (-Cprofile-generate)")
    sc.add_argument("--scratch", required=True)
    sc.add_argument("--chunk", type=int, default=60)
    sc.add_argument("--timeout", type=float, default=120.0)
    sc.add_argument("--llvm-profdata", default=None)
    sc.set_defaults(fn=cmd_scan)

    s = sub.add_parser("select")
    s.add_argument("arm")
    s.add_argument("--count", action="store_true")
    s.add_argument("--sources", action="store_true")
    s.set_defaults(fn=cmd_select)

    r = sub.add_parser("run")
    r.add_argument("arm")
    r.add_argument("--binary", required=True)
    r.add_argument("--profile-file", default=None,
                   help="LLVM_PROFILE_FILE for the child processes")
    r.add_argument("--timeout", type=float, default=60.0)
    r.add_argument("--log", default=None)
    r.add_argument("--progress", action="store_true")
    r.set_defaults(fn=cmd_run)

    args = p.parse_args()
    args.fn(args)


if __name__ == "__main__":
    main()
