#!/usr/bin/env bash
#
# Headroom sweep on the toy PGO baseline (SPEC.ja.md 6.3, 13 day-0 item 5).
#
# Every configuration is the PGO baseline plus one (rarely two) -Cllvm-args
# knobs: same merged.profdata, same debuginfo=1, same panic strategy, same
# remark flags, explicit --target, its own CARGO_TARGET_DIR, clean build.
#
# Primary read is the remark diff (SPEC.ja.md 6.3): dump the sorted `remark:`
# lines of the build log and compare to the baseline's. A configuration whose
# remarks are unchanged did not change a decision and skips timing. Secondary
# read is the interleaved timing of the configurations that did change.
#
# Phases:
#   build   build every configuration, collect checksums, .text hashes and
#           remark diffs                                 (BUILD=0 to skip)
#   time    one interleaved bench.py run over the baseline plus every
#           configuration that changed something         (TIME=0 to skip)
#
# Usage:  scripts/toy_headroom.sh
#         BUILD=0 scripts/toy_headroom.sh          # re-time only
#         MDE=0.031 scripts/toy_headroom.sh        # override the frozen MDE
set -euo pipefail

source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/toy_common.sh"

OUT="$REPO/artifacts/$TARGET-headroom"
SWEEP_TD="$REPO/target-$TARGET-headroom"
BUILD="${BUILD:-1}"
TIME="${TIME:-1}"
RUNS="${RUNS:-10}"
WARMUP="${WARMUP:-3}"
AA_STATS="$REPO/artifacts/$TARGET-aa/aa-stats.json"

# The sweep. One knob per configuration except where a combination is the
# point. Knob names and enum values come from llvm-knobs.json, generated by
# scripts/gen_llvm_knobs.sh from the pinned toolchain; values that are already
# the compiler default are not swept (the baseline is that configuration).
#
# SPEC.ja.md 6.3 group 1 lists `-prefer-predicate-over-epilogue`. That cl::opt
# does not exist on LLVM 23.1.1. Its 23.1.1 successors are used instead:
# -epilogue-tail-folding-policy and -force-tail-folding-style.
CONFIGS=(
  # group 0: noise probe, no decision content
  "g0-align5|-align-all-nofallthru-blocks=5"
  # group 1: vectorizer
  "g1-maxbw|-vectorizer-maximize-bandwidth"
  "g1-vw8|-force-vector-width=8"
  "g1-vw16|-force-vector-width=16"
  "g1-vw32|-force-vector-width=32"
  "g1-maxbw-vw32|-vectorizer-maximize-bandwidth -force-vector-width=32"
  "g1-ic1|-force-vector-interleave=1"
  "g1-ic2|-force-vector-interleave=2"
  "g1-ic4|-force-vector-interleave=4"
  "g1-tailfold-prefer|-epilogue-tail-folding-policy=prefer-fold-tail"
  "g1-tfstyle-data|-force-tail-folding-style=data"
  "g1-tfstyle-data-and-control|-force-tail-folding-style=data-and-control"
  "g1-memcheck24|-runtime-memory-check-threshold=24"
  "g1-memcheck128|-runtime-memory-check-threshold=128"
  "g1-earlyexit|-enable-early-exit-vectorization"
  # group 2: inlining and unrolling
  "g2-inline325|-inline-threshold=325"
  "g2-inline500|-inline-threshold=500"
  "g2-inline1000|-inline-threshold=1000"
  "g2-unroll-thr300|-unroll-threshold=300"
  "g2-unroll-thr1000|-unroll-threshold=1000"
  "g2-unroll-max2|-unroll-max-count=2"
  "g2-unroll-max8|-unroll-max-count=8"
  "g2-unroll-runtime|-unroll-runtime"
  # group 3: the rest
  "g3-loop-distribute|-enable-loop-distribute"
  "g3-slp-neg20|-slp-threshold=-20"
  "g3-slp-100|-slp-threshold=100"
  "g3-unswitch200|-unswitch-threshold=200"
  "g3-loop-flatten|-enable-loop-flatten"
  "g3-gvn-hoist|-enable-gvn-hoist"
)

# DebugLocs of the four toy loops on the PGO baseline (results.md Day 0 section
# 6). Used to pull each configuration's decision for each loop out of its log.
# The column is part of the key where the file is std's (that DebugLoc is
# shared by every inlined instance of that std loop, SPEC.ja.md 7); objdump is
# what settles which loop a decision belongs to.
declare -A LOOP_LOC=(
  [count_quotes]="library/core/src/slice/iter/macros.rs:279:24"
  [find_special]="toyloops/src/lib.rs:26"
  [sum_indexed]="library/core/src/iter/range.rs:1103:12"
  [dot_f64]="toyloops/src/lib.rs:50"
)

mkdir -p "$OUT/bin" "$OUT/strip" "$OUT/remarks" "$REMARK_DIR"

# ---------------------------------------------------------------------------
# build phase
# ---------------------------------------------------------------------------
build_one() {           # build_one <name> <knob args...>
  local name="$1"; shift
  local log="$REMARK_DIR/$name-build.log"
  local td="$SWEEP_TD/$name"
  local t0 t1 rc=0
  t0=$(date +%s%N)
  build_variant "$td" "$log" "$@" || rc=$?
  t1=$(date +%s%N)
  printf '%-30s %5d ms  rc=%d\n' "$name" $(( (t1-t0)/1000000 )) "$rc"
  if [ "$rc" != 0 ]; then
    echo "$name" >> "$OUT/build-failures.txt"
    tail -5 "$log" | sed 's/^/      /'
    return 0
  fi
  cp "$td/$TRIPLE/release/$BIN_NAME" "$OUT/bin/$name"
  cp "$OUT/bin/$name" "$OUT/strip/$name"
  strip -s "$OUT/strip/$name"
  remark_set "$log" "$OUT/remarks/$name.raw"
  remark_set_normalized "$log" "$OUT/remarks/$name.norm"
  # Correctness: the checksums must match the baseline's (SPEC.ja.md 10).
  "$OUT/bin/$name" all > "$OUT/remarks/$name.checksums" 2>&1 || echo "RUN FAILED" >> "$OUT/remarks/$name.checksums"
  text_hash "$OUT/bin/$name" > "$OUT/remarks/$name.texthash"
  rm -rf "$td"
}

if [ "$BUILD" = 1 ]; then
  rm -rf "$OUT" "$SWEEP_TD"
  mkdir -p "$OUT/bin" "$OUT/strip" "$OUT/remarks"
  echo "== baseline =="
  build_one baseline
  echo "== sweep: ${#CONFIGS[@]} configurations =="
  for entry in "${CONFIGS[@]}"; do
    name="${entry%%|*}"
    args="${entry#*|}"
    # shellcheck disable=SC2086
    build_one "$name" $args
  done
fi

# ---------------------------------------------------------------------------
# analysis: checksums, .text hashes, remark diffs
# ---------------------------------------------------------------------------
BASE_SUM="$OUT/remarks/baseline.checksums"
BASE_TEXT="$(cat "$OUT/remarks/baseline.texthash")"
SUMMARY="$OUT/summary.tsv"
printf 'config\tknobs\tchecksums\ttext_vs_base\traw_added\traw_removed\tnorm_added\tnorm_removed\tdecision_change\n' > "$SUMMARY"

loop_decisions() {      # loop_decisions <name>  -> "count_quotes=...; ..."
  local name="$1" out=""
  for fn in count_quotes find_special sum_indexed dot_f64; do
    local loc="${LOOP_LOC[$fn]}"
    local d
    d=$( { grep -F "$loc" "$OUT/remarks/$name.norm" || true; } \
        | sed -E 's/^remark: [^ ]+ //' | sort -u | paste -sd'/' -)
    out+="$fn={${d:-none}}; "
  done
  printf '%s' "$out"
}

loop_decisions baseline > "$OUT/baseline-decisions.txt"

TIMING_SET=(baseline)
for entry in "${CONFIGS[@]}"; do
  name="${entry%%|*}"; knobs="${entry#*|}"
  if [ ! -f "$OUT/remarks/$name.norm" ]; then
    printf '%s\t%s\tBUILD-FAILED\t-\t-\t-\t-\t-\t-\n' "$name" "$knobs" >> "$SUMMARY"
    continue
  fi
  if diff -q "$BASE_SUM" "$OUT/remarks/$name.checksums" >/dev/null; then sums=MATCH; else sums=MISMATCH; fi
  if [ "$(cat "$OUT/remarks/$name.texthash")" = "$BASE_TEXT" ]; then th=same; else th=differ; fi
  ra=$(comm -13 "$OUT/remarks/baseline.raw" "$OUT/remarks/$name.raw" | wc -l)
  rr=$(comm -23 "$OUT/remarks/baseline.raw" "$OUT/remarks/$name.raw" | wc -l)
  na=$(comm -13 "$OUT/remarks/baseline.norm" "$OUT/remarks/$name.norm" | wc -l)
  nr=$(comm -23 "$OUT/remarks/baseline.norm" "$OUT/remarks/$name.norm" | wc -l)
  loop_decisions "$name" > "$OUT/remarks/$name.decisions"
  if diff -q "$OUT/baseline-decisions.txt" "$OUT/remarks/$name.decisions" >/dev/null; then dc=no; else dc=YES; fi
  printf '%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\n' "$name" "$knobs" "$sums" "$th" "$ra" "$rr" "$na" "$nr" "$dc" >> "$SUMMARY"
  # Timing set: group 0 always (it is the in-sweep noise probe), plus anything
  # whose normalized remarks or whose .text changed. A configuration with an
  # identical .text is the same machine code and cannot differ in time.
  if [ "${name#g0-}" != "$name" ] || [ "$na" != 0 ] || [ "$nr" != 0 ] || [ "$th" = differ ]; then
    TIMING_SET+=("$name")
  fi
done

column -t -s$'\t' "$SUMMARY" | tee "$OUT/summary.txt"
echo
echo "baseline loop decisions: $(cat "$OUT/baseline-decisions.txt")"
echo
echo "timing set (${#TIMING_SET[@]}): ${TIMING_SET[*]}"
printf '%s\n' "${TIMING_SET[@]}" > "$OUT/timing-set.txt"

# ---------------------------------------------------------------------------
# timing phase
# ---------------------------------------------------------------------------
[ "$TIME" = 1 ] || exit 0

if [ -z "${MDE:-}" ] && [ -f "$AA_STATS" ]; then
  MDE=$(python3 -c "import json,sys;print(json.load(open(sys.argv[1]))['mde'])" "$AA_STATS")
fi
MDE="${MDE:-0.03}"
echo "frozen MDE from $AA_STATS: $MDE"

LBL=()
while read -r n; do LBL+=(--label "$n=$OUT/strip/$n"); done < "$OUT/timing-set.txt"
WL=()
for w in "${WORKLOADS[@]}"; do WL+=(--workload "$w"); done

"$REPO/scripts/bench.py" run \
  --cpu "$BENCH_CPU" --warmup "$WARMUP" --runs "$RUNS" \
  "${LBL[@]}" "${WL[@]}" --out "$OUT/headroom.json" --progress

"$REPO/scripts/bench.py" stats "$OUT/headroom.json" --base baseline \
  --seed 20260921 --resamples 10000 --mde "$MDE" \
  --json "$OUT/headroom-stats.json" | tee "$OUT/headroom-stats.md"
